### ISSUE TITLE
cannot open interactive.ipynb

### ISSUE THREAD

**Issue by NIRVANALAN** [shchur/overlapping-community-detection#1]
Notebook JSON is invalid: 'ename' is a required property
Could you specify the version of jupyter notebook you use?

**Comment by shchur** [comment]
I have the following packages installed in my Conda environment
```
jupyter                   1.0.0                    py37_7
jupyter_client            5.3.4                    py37_0
jupyter_console           6.0.0                    py37_0
notebook                  6.0.1                    py37_0
```
If everything else fails, it should be possible to [preview the notebook on Github](https://github.com/shchur/overlapping-community-detection/blob/master/interactive.ipynb)

**Comment by NIRVANALAN** [comment]
Thanks, problem solved🙏
________________________________
